services:
  db:
    image: postgres:latest
    container_name: visualizer-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_db:/var/lib/postgresql/data

  # redis:
  #   image: redis:7
  #   container_name: heimdall-redis
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - heimdall-network

volumes:
  postgres_db:
